name: CI-CD Workflow

on:
  push:
    branches:
      - '**'
    paths:
        - 'client/**'
  pull_request:
    branches:
      - '**'
    paths:
        - 'client/**'

jobs:
  frontend:
    name: Frontend CI
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./client

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup for node
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install node modules
      run: npm install

    - name: Run jest tests
      run: npm test
